version: "3"

services:
  database:
    image: mysql:8.0
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password

  app:
    build: .
    tty: true
    ports:
      - 8000:8000
    volumes:
      - .:/usr/src/app
